apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapplication
  labels:
    app: httpd
    tier : frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
      tier: frontend
  template:
    metadata:
      labels:
        app: httpd
        tier : frontend
    spec:
      containers:
      - name: stack_httpd
        image: lakshmaiah212/stack_httpd:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "50m"                
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        failureThreshold: 5
        periodSeconds: 1