---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.94.5
    path: "/export/volumes/pod"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvc-demo
  labels:
    tier: frontend
    app: nginx
spec: 
  replicas: 5
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      volumes:
      - name: webcontent
        persistentVolumeClaim:
          claimName:  pvc-demo
      containers :
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
          volumeMounts:
            - name: webcontent
              mountPath: "/usr/share/nginx/html/webapp"
---
apiVersion: v1
kind: Service
metadata:
  name: pv-demo-svc
spec: 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 80
  selector:
    app: nginx
    tier: frontend