apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-Hostpath
  label:
    type: local
spec:
  storgeClassName:  manual
  capacity: 
    storage:  "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"